[package]
name = "wasmtime-provider"
version = "0.0.2"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
exclude = [".assets"]
description = "A wasmtime engine provider for the waPC host"
license = "Apache-2.0"
homepage = "https://github.com/wapc/wasmtime-provider"
documentation = "https://docs.rs/wasmtime-provider"
readme = "README.md"
keywords = ["sdk", "wapc", "webassembly", "wasm", "wasmtime"]
categories = ["wasm", "api-bindings"]


[dependencies]
wapc = "0.10.1"
log = "0.4.11"
env_logger = "0.7"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
wasmtime = "0.19.0"
wasmtime-wasi = "0.19.1"
anyhow = "1.0.31"
wasi-common = "0.19.1"