name: release
on:
  push:
    tags:
      - "wapc-codec-v[0-9]+.[0-9]+.[0-9]+"
      - "wapc-guest-v[0-9]+.[0-9]+.[0-9]+"
      - "wapc-pool-v[0-9]+.[0-9]+.[0-9]+"
      - "wapc-v[0-9]+.[0-9]+.[0-9]+"
      - "wasm3-provider-v[0-9]+.[0-9]+.[0-9]+"
      - "wasmtime-provider-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    name: publish to crates.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - wapc
          - wapc-codec
          - wapc-guest
          - wapc-pool
          - wasm3-provider
          - wasmtime-provider

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: publish ${{ matrix.crate }} to crates.io
        if: startsWith(github.ref, format('refs/tags/{0}-v', matrix.crate))
        run: cargo publish --token ${{ secrets.CARGOTOKEN }}
        working-directory: ./crates/${{ matrix.crate }}
